// SPDX-License-Identifier: GPL-3.0-or-later
//
// Every script in scripts/ is compiled and run here.
//
// The directory is a shop: the site lists it, and people are invited to add to
// it by pull request. A shop that ships a script which does not compile is
// worse than a shop with nothing in it - somebody pastes it into their device,
// gets a red dot and a compiler error, and has no way to know whether the
// fault is theirs. So every script is run against the real engine, on the real
// panel size, before it can be merged.
//
// This is also the only test that would catch a builtin being renamed out from
// under the examples.
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include <cstdint>
#include <string_view>

#include "stipple/apps/BatteryApp.h"
#include "stipple/apps/ClockApp.h"
#include "stipple/apps/StopwatchApp.h"
#include "stipple/graphics/Canvas.h"
#include "stipple/imageio/Png.h"
#include "stipple/platform/PlatformServices.h"
#include "stipple/mqtt/ScriptGateway.h"
#include "stipple/net/ScriptFetcher.h"
#include "stipple/net/HttpFetch.h"
#include "stipple/platform/simulator/SimulatorHttpClient.h"
#include "stipple/platform/simulator/SimulatorPlatform.h"
#include "stipple/platform/MqttClient.h"
#include "stipple/graphics/Framebuffer.h"
#include "stipple/text/Text.h"
#include "stipple/script/ScriptHost.h"
#include "stipple/script/ScriptStore.h"
#include "support/TestFramework.h"

using stipple::Canvas;
using stipple::Framebuffer;
using stipple::script::ScriptStore;
namespace colors = stipple::colors;

namespace {

#ifndef STIPPLE_SCRIPTS_DIR
#define STIPPLE_SCRIPTS_DIR "scripts"
#endif

struct Example {
    std::string name;
    std::string source;
};

std::string readFile(const std::string& path) {
    std::string out;
    std::FILE* file = std::fopen(path.c_str(), "rb");
    if (file == nullptr) {
        return out;
    }
    char buffer[4096];
    std::size_t got = 0;
    while ((got = std::fread(buffer, 1, sizeof(buffer), file)) > 0) {
        out.append(buffer, got);
    }
    std::fclose(file);
    return out;
}

/// The names in scripts/, baked in at configure time.
///
/// Generated by CMake rather than scanned at runtime. A scan would quietly
/// pass if the binary ran from somewhere unexpected - "no scripts found,
/// nothing to check, all good" is the exact shape of a test that has stopped
/// testing. Baked-in names fail loudly instead, and an empty directory is a
/// configure error.
///
/// The list used to be written out by hand so that the shop page could not
/// list a script nobody ran. Generating both from the same directory gives
/// that by construction, and adding a script is now just adding the file.
#ifndef STIPPLE_SHOP_SCRIPT_LIST
#define STIPPLE_SHOP_SCRIPT_LIST "battery.be",
#endif

const char* kExampleFiles[] = {STIPPLE_SHOP_SCRIPT_LIST};

std::vector<Example> loadExamples() {
    std::vector<Example> examples;
    for (const char* name : kExampleFiles) {
        Example example;
        example.name = name;
        example.source = readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/" + name);
        examples.push_back(std::move(example));
    }
    return examples;
}

int countLit(const Framebuffer& framebuffer) {
    int lit = 0;
    for (int y = 0; y < Framebuffer::kHeight; ++y) {
        for (int x = 0; x < Framebuffer::kWidth; ++x) {
            if (framebuffer.at(x, y) != colors::kBlack) { ++lit; }
        }
    }
    return lit;
}

}  // namespace

STIPPLE_TEST(ShopScripts, EveryPublishedScriptCompilesAndDraws) {
    const std::vector<Example> examples = loadExamples();
    STIPPLE_REQUIRE(!examples.empty());

    for (const Example& example : examples) {
        // A missing file is a failure, not a skip.
        STIPPLE_REQUIRE(!example.source.empty());

        ScriptStore store;
        stipple::script::ScriptEnvironment environment;
        environment.timeKnown = true;
        environment.hour = 14;
        environment.minute = 37;
        environment.second = 22;
        environment.day = 9;
        environment.month = 11;
        environment.year = 2025;
        environment.weekday = 0;
        environment.batteryKnown = true;
        environment.batteryPercent = 64;
        environment.charging = true;
        store.setEnvironment(environment);

        const auto result = store.put("shop", example.name, example.source);
        if (result != stipple::script::ScriptPutResult::Added) {
            std::printf("    [shop] %s: %s\n", example.name.c_str(),
                        store.find("shop") != nullptr
                            ? store.find("shop")->problem.c_str()
                            : "would not store");
        }
        STIPPLE_REQUIRE(result == stipple::script::ScriptPutResult::Added);

        // Ninety frames, three seconds at thirty. Long enough for an
        // animation to wrap, a pipe to cross the panel and a blink to blink -
        // a script that only fails on its second cycle is one the shop would
        // otherwise ship.
        Framebuffer framebuffer;
        Canvas canvas(framebuffer);
        int litSomething = 0;
        for (int frame = 0; frame < 90; ++frame) {
            // The device clock advances with the frames.
            //
            // Scripts throttle on now_ms(), so a harness that left it at zero
            // would drive every one of them at a standstill - they would draw
            // their first frame ninety times and pass every check here. The
            // previews on the shop page come from this same loop, so it would
            // have published a page of still images of moving things.
            environment.monotonicMillis = static_cast<std::uint64_t>(frame) * 33u;
            store.setEnvironment(environment);

            const bool drew =
                store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);
            if (!drew) {
                std::printf("    [shop] %s failed on frame %d: %s\n", example.name.c_str(),
                            frame, store.find("shop")->problem.c_str());
            }
            STIPPLE_REQUIRE(drew);
            litSomething += countLit(framebuffer) > 0 ? 1 : 0;

            // Press the button every so often, so a script with an
            // on_button is exercised in play rather than watched falling to
            // its death. It also means the handler's own instruction budget
            // and stack balance are covered for every published script, not
            // only for the ones in the unit tests.
            //
            // **"select", because that is the name ApplicationHost sends.**
            // This said "action" for a long time, and every published script
            // guards its handler with `if name != "select" return`, so the
            // press arrived, was rejected on the first line, and the test
            // proved nothing about the code underneath. A whole class of
            // handler bug could not fail here - and one did reach a device,
            // where pressing the button killed the script outright.
            //
            // A script declaring `# @input exclusive` (ADR 0024) receives four
            // more names, so it gets all five in rotation. Pressing only
            // "select" at a game would cover the serve and never the paddle -
            // the same shape of hole as the "action" bug above, and it would
            // reach a device the same way.
            if (frame % 11 == 0) {
                static const char* kExclusive[] = {"select", "left", "right",
                                                   "minus", "plus"};
                const bool takesAll = store.inputMode("shop") ==
                                      stipple::script::InputMode::Exclusive;
                const char* name =
                    takesAll ? kExclusive[(frame / 11) % 5] : "select";
                store.button("shop", name);
            }
        }

        // And it actually drew. A script that compiles, runs and leaves the
        // panel black passes every check above and is still broken.
        STIPPLE_CHECK(litSomething > 0);
    }
}

STIPPLE_TEST(ShopScripts, NoneOfThemLeak) {
    // Same reasoning as the builtin leak guard, applied to the code people
    // will actually copy. A published script that grows its live set every
    // frame takes the device down after a day, and the person who installed
    // it has no reason to suspect the script.
    for (const Example& example : loadExamples()) {
        STIPPLE_REQUIRE(!example.source.empty());

        ScriptStore store;
        STIPPLE_REQUIRE(store.put("shop", example.name, example.source) ==
                        stipple::script::ScriptPutResult::Added);

        // The clock advances here too: a script frozen at time zero allocates
        // nothing after its first frame, so a leak guard driving one would be
        // guarding nothing.
        stipple::script::ScriptEnvironment moving;
        Framebuffer framebuffer;
        Canvas canvas(framebuffer);
        for (int frame = 0; frame < 120; ++frame) {
            moving.monotonicMillis = static_cast<std::uint64_t>(frame) * 33u;
            store.setEnvironment(moving);
            store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);
        }
        store.collectGarbage("shop");
        const std::size_t before = store.find("shop")->memoryBytes;

        for (int frame = 0; frame < 600; ++frame) {
            moving.monotonicMillis = static_cast<std::uint64_t>(120 + frame) * 33u;
            store.setEnvironment(moving);
            const bool drew =
                store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);

            // Checked here as well as in the compile test, because this is
            // the only loop long enough to reach a steady state. A script
            // that accumulates - a pile of sand, a filling well - costs more
            // per frame the fuller it gets, and its most expensive frame is
            // nowhere near the first ninety.
            //
            // That is exactly how Sandbox shipped a script that died when
            // somebody pressed the button: three seconds in, the pile was
            // small and the shake was cheap.
            if (!drew) {
                std::printf("    [shop] %s died on frame %d of 600: %s\n",
                            example.name.c_str(), frame,
                            store.find("shop")->problem.c_str());
            }
            STIPPLE_REQUIRE(drew);

            // Not checked for a return: false also means "this script has
            // no on_button", which most of them do not. What matters is that
            // the frame after a press still draws, which the check above
            // does for every frame.
            if (frame % 37 == 0) {
                store.button("shop", "select");
            }
        }
        store.collectGarbage("shop");
        const std::size_t after = store.find("shop")->memoryBytes;

        if (after > before) {
            std::printf("    [shop] %s grew %zu -> %zu over 600 frames\n",
                        example.name.c_str(), before, after);
        }
        // Some slack: a script that legitimately holds a list of stars will
        // settle at a size, and the settling can straddle the first
        // collection. Growth of kilobytes is a leak; a few hundred bytes once
        // is a data structure finding its shape.
        STIPPLE_CHECK(after <= before + 512u);
    }
}

STIPPLE_TEST(ShopScripts, EachOneSaysWhenTheDeviceCannotTellItTheTime) {
    // The examples are what people copy, so they are where the honesty about
    // absence has to be demonstrated rather than described. A clock script
    // that draws 00:00 on a device with no time has invented it, and anybody
    // starting from that script inherits the bug. ADR 0013.
    const char* needTime[] = {"big-clock.be", "binary-clock.be", "day-progress.be"};

    for (const char* name : needTime) {
        const std::string source = readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/" + name);
        STIPPLE_REQUIRE(!source.empty());

        ScriptStore store;
        // Default environment: the clock has never been set.
        STIPPLE_REQUIRE(store.put("shop", name, source) ==
                        stipple::script::ScriptPutResult::Added);

        Framebuffer framebuffer;
        Canvas canvas(framebuffer);
        STIPPLE_REQUIRE(store.draw("shop", canvas, 0));

        // It says something rather than drawing a time it does not have.
        const int lit = countLit(framebuffer);
        if (lit == 0) {
            std::printf("    [shop] %s draws nothing when the time is unknown\n", name);
        }
        STIPPLE_CHECK(lit > 0);
    }
}

namespace {

/// A broker that goes nowhere. Enough for a gateway to call itself
/// connected, which is all either harness below needs of it.
class NowhereBroker final : public stipple::platform::IMqttClient {
public:
    bool connect(const stipple::platform::MqttConnectOptions&,
                 stipple::platform::IMqttListener&) override {
        return true;
    }
    void disconnect() override {}
    stipple::platform::MqttState state() const override {
        return stipple::platform::MqttState::Connected;
    }
    bool publish(const stipple::platform::MqttMessage&) override { return true; }
    bool subscribe(std::string_view filter, int) override {
        watched.emplace_back(filter);
        return true;
    }
    void poll(std::uint64_t) override {}
    bool supportsTls() const override { return false; }

    std::vector<std::string> watched;
};

/// A speaker that takes everything and remembers nothing. The audio gate
/// below cares only whether one is present, not what came out of it.
class SilentSpeaker final : public stipple::platform::IAudioOutput {
public:
    bool playTone(int, int) override { return true; }
    bool playSound(std::string_view) override { return true; }
    void stop() override {}
    void setVolume(std::uint8_t volume) override { level_ = volume; }
    std::uint8_t volume() const override { return level_; }

private:
    std::uint8_t level_ = 128;
};

}  // namespace

STIPPLE_TEST(ShopScripts, EachAudioScriptSaysWhenTheDeviceCannotMakeASound) {
    // The same rule as the clock, one capability along. A metronome on a
    // device with no speaker is a swinging pendulum and nothing else, and
    // somebody watching it cannot tell that from a metronome whose volume
    // is down - unless the script says so. ADR 0013.
    //
    // Checking that it draws *something* would pass a script that ignored
    // the question entirely, so this renders the same frame twice, once
    // with a speaker and once without, and requires the two to differ.
    const char* needAudio[] = {"metronome.be", "kitchen-timer.be", "sequencer.be",
                               "pomodoro.be"};

    for (const char* name : needAudio) {
        const std::string source = readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/" + name);
        STIPPLE_REQUIRE(!source.empty());

        Framebuffer heard;
        Framebuffer silent;

        {
            ScriptStore store;
            SilentSpeaker speaker;
            store.setAudio(&speaker);
            STIPPLE_REQUIRE(store.put("shop", name, source) ==
                            stipple::script::ScriptPutResult::Added);
            Canvas canvas(heard);
            STIPPLE_REQUIRE(store.draw("shop", canvas, 0));
        }

        {
            ScriptStore store;  // no audio at all
            STIPPLE_REQUIRE(store.put("shop", name, source) ==
                            stipple::script::ScriptPutResult::Added);
            Canvas canvas(silent);
            STIPPLE_REQUIRE(store.draw("shop", canvas, 0));
        }

        STIPPLE_CHECK(countLit(silent) > 0);
        if (heard == silent) {
            std::printf("    [shop] %s draws the same frame with and without a speaker\n",
                        name);
        }
        STIPPLE_CHECK(!(heard == silent));
    }
}

STIPPLE_TEST(ShopScripts, EachMqttScriptSaysWhenThereIsNoBroker) {
    // Third time the same rule. MQTT is off by default, so this is not the
    // unlikely case - it is what every one of these scripts does on the day
    // somebody first pastes it in, and a panel that goes black then is
    // indistinguishable from one that crashed.
    const char* needBroker[] = {"power-meter.be"};

    for (const char* name : needBroker) {
        const std::string source = readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/" + name);
        STIPPLE_REQUIRE(!source.empty());

        Framebuffer connected;
        Framebuffer alone;

        {
            NowhereBroker broker;
            stipple::mqtt::ScriptGateway gateway;
            gateway.setClient(&broker);
            gateway.setBase("stipple/demo");
            gateway.setConnected(true);

            ScriptStore store;
            store.setMqtt(&gateway);
            STIPPLE_REQUIRE(store.put("shop", name, source) ==
                            stipple::script::ScriptPutResult::Added);
            Canvas canvas(connected);
            STIPPLE_REQUIRE(store.draw("shop", canvas, 0));
        }

        {
            ScriptStore store;  // no gateway at all
            STIPPLE_REQUIRE(store.put("shop", name, source) ==
                            stipple::script::ScriptPutResult::Added);
            Canvas canvas(alone);
            STIPPLE_REQUIRE(store.draw("shop", canvas, 0));
        }

        STIPPLE_CHECK(countLit(alone) > 0);
        if (connected == alone) {
            std::printf("    [shop] %s draws the same frame with and without a broker\n",
                        name);
        }
        STIPPLE_CHECK(!(connected == alone));
    }
}

STIPPLE_TEST(ShopScripts, EachMicScriptSaysWhenTheDeviceCannotHear) {
    // A visualiser on a deaf device draws a flat line, which is exactly what
    // a visualiser in a silent room draws. Only the script can tell you which
    // one you are looking at. ADR 0013.
    const char* needEars[] = {"neon-bars.be"};

    for (const char* name : needEars) {
        const std::string source = readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/" + name);
        STIPPLE_REQUIRE(!source.empty());

        Framebuffer heard;
        Framebuffer deaf;

        {
            stipple::platform::simulator::SimulatorMicrophone microphone;
            microphone.hear(9000);
            ScriptStore store;
            store.setMicrophone(&microphone);
            STIPPLE_REQUIRE(store.put("shop", name, source) ==
                            stipple::script::ScriptPutResult::Added);
            Canvas canvas(heard);
            STIPPLE_REQUIRE(store.draw("shop", canvas, 0));
        }

        {
            ScriptStore store;  // no microphone at all
            STIPPLE_REQUIRE(store.put("shop", name, source) ==
                            stipple::script::ScriptPutResult::Added);
            Canvas canvas(deaf);
            STIPPLE_REQUIRE(store.draw("shop", canvas, 0));
        }

        STIPPLE_CHECK(countLit(deaf) > 0);
        STIPPLE_CHECK(!(heard == deaf));
    }
}

STIPPLE_TEST(ShopScripts, EachHttpScriptSaysWhenItCannotFetch) {
    const char* needNetwork[] = {"weather.be", "daylight.be", "youtube.be",
                                 "github.be"};

    for (const char* name : needNetwork) {
        const std::string source = readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/" + name);
        STIPPLE_REQUIRE(!source.empty());

        ScriptStore store;  // no fetcher at all
        STIPPLE_REQUIRE(store.put("shop", name, source) ==
                        stipple::script::ScriptPutResult::Added);

        Framebuffer framebuffer;
        Canvas canvas(framebuffer);
        STIPPLE_REQUIRE(store.draw("shop", canvas, 0));

        // It says something rather than going black, which is what a device
        // that crashed also does.
        if (countLit(framebuffer) == 0) {
            std::printf("    [shop] %s draws nothing when it cannot fetch\n", name);
        }
        STIPPLE_CHECK(countLit(framebuffer) > 0);
    }
}

STIPPLE_TEST(ShopScripts, TheGitHubScriptReadsAFullYearOfContributions) {
    // A real-sized body, not a token one. The whole design of this script is
    // about the 15 KB the contributions API actually sends: it splits on
    // `"level":` instead of parsing JSON, because building 365 Berry maps in
    // one frame would cost the frame. A three-entry fixture would prove none
    // of that.
    const std::string source =
        readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/github.be");
    STIPPLE_REQUIRE(!source.empty());

    std::string body = R"({"total":{"lastYear":928},"contributions":[)";
    for (int i = 0; i < 365; ++i) {
        if (i > 0) { body += ','; }
        // Levels cycle so every shade is exercised, and the count field is
        // present because the real one has it and it is what makes the
        // payload big.
        body += R"({"date":"2026-01-01","count":)" + std::to_string(i % 17) +
                R"(,"level":)" + std::to_string(i % 5) + "}";
    }
    body += "]}";
    STIPPLE_REQUIRE(body.size() > 12000);
    STIPPLE_REQUIRE(body.size() < stipple::net::http::ResponseParser::kMaxBodyBytes);

    stipple::platform::simulator::SimulatorHttpClient client;
    stipple::net::ScriptFetcher fetcher;
    fetcher.setClient(&client);
    fetcher.setNetworkUp(true);

    stipple::script::ScriptEnvironment environment;
    environment.timeKnown = true;
    environment.year = 2026;
    environment.month = 9;
    environment.day = 28;
    environment.weekday = 1;

    ScriptStore store;
    store.setHttp(&fetcher);
    store.setEnvironment(environment);
    STIPPLE_REQUIRE(store.put("shop", "github.be", source) ==
                    stipple::script::ScriptPutResult::Added);

    Framebuffer waiting;
    Canvas waitingCanvas(waiting);
    STIPPLE_REQUIRE(store.draw("shop", waitingCanvas, 0));
    STIPPLE_REQUIRE(fetcher.feedCount() == 1);

    fetcher.tick(0);
    STIPPLE_REQUIRE(!client.asked().empty());
    // The declared default username, and the year off the clock.
    STIPPLE_CHECK(client.asked().front().find("galadril") != std::string::npos);
    STIPPLE_CHECK(client.asked().front().find("y=2026") != std::string::npos);

    stipple::platform::simulator::SimulatorHttpClient::Route route;
    route.url = client.asked().front();
    route.latencyMillis = 0;
    route.body = body;
    client.answer(route);

    for (std::uint64_t now = 0;
         now < stipple::net::ScriptFetcher::kFailureBackoffMillis + 2000; now += 100) {
        fetcher.tick(now);
    }

    Framebuffer drawn;
    Canvas canvas(drawn);
    STIPPLE_REQUIRE(store.draw("shop", canvas, 33));
    STIPPLE_CHECK(store.problem("shop").empty());

    // The grid occupies the top seven rows and every column, so a parse that
    // produced nothing would leave them black.
    int grid = 0;
    for (int y = 0; y < 7; ++y) {
        for (int x = 0; x < Framebuffer::kWidth; ++x) {
            if (drawn.at(x, y) != colors::kBlack) { ++grid; }
        }
    }
    if (grid < 200) {
        std::printf("    [shop] github.be lit only %d of 364 grid pixels\n",
                    grid);
    }
    STIPPLE_CHECK(grid > 200);

    // And the headline number, pixel-exact.
    Framebuffer expected;
    Canvas expectedCanvas(expected);
    stipple::text::drawLine(expectedCanvas, "928", 0, 9,
                            stipple::text::font5x7(), stipple::colors::kWhite);

    int overlap = 0;
    int wanted = 0;
    for (int y = 0; y < Framebuffer::kHeight; ++y) {
        for (int x = 0; x < Framebuffer::kWidth; ++x) {
            if (expected.at(x, y) != colors::kBlack) {
                ++wanted;
                if (drawn.at(x, y) != colors::kBlack) { ++overlap; }
            }
        }
    }
    STIPPLE_REQUIRE(wanted > 0);
    STIPPLE_CHECK(overlap == wanted);

    // Parsing is not repeated on every frame. Fifteen kilobytes through
    // string.split once is affordable; thirty times a second is not, and the
    // only signal a script gets that the body changed is the age resetting.
    const std::uint32_t after = store.find("shop")->lastInstructions;
    Canvas again(drawn);
    STIPPLE_REQUIRE(store.draw("shop", again, 66));
    STIPPLE_CHECK(store.find("shop")->lastInstructions <= after);
}

STIPPLE_TEST(ShopScripts, TheYouTubeScriptReadsARealSocialCountsReply) {
    // Recorded from api.socialcounts.org, byte for byte. The nesting is the
    // fragile part - counters.api.subscriberCount, with an `estimation`
    // sibling that is a guess rather than a published figure - and nothing
    // else in the suite would notice if that shape changed.
    const std::string source =
        readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/youtube.be");
    STIPPLE_REQUIRE(!source.empty());

    stipple::platform::simulator::SimulatorHttpClient client;
    stipple::net::ScriptFetcher fetcher;
    fetcher.setClient(&client);
    fetcher.setNetworkUp(true);

    ScriptStore store;
    store.setHttp(&fetcher);
    STIPPLE_REQUIRE(store.put("shop", "youtube.be", source) ==
                    stipple::script::ScriptPutResult::Added);

    Framebuffer waiting;
    Canvas waitingCanvas(waiting);
    STIPPLE_REQUIRE(store.draw("shop", waitingCanvas, 0));
    STIPPLE_REQUIRE(fetcher.feedCount() == 1);

    fetcher.tick(0);
    STIPPLE_REQUIRE(!client.asked().empty());

    // The URL carries the declared default channel, which is also the check
    // that `@config` reached the script at all.
    STIPPLE_CHECK(client.asked().front().find("UCpGLALzRO0uaasWTsm9M99w") !=
                  std::string::npos);

    stipple::platform::simulator::SimulatorHttpClient::Route route;
    route.url = client.asked().front();
    route.latencyMillis = 0;
    route.body =
        R"({"counters":{"estimation":{"subscriberCount":424,"viewCount":374271,)"
        R"("videoCount":109},"api":{"subscriberCount":424,"viewCount":374263,)"
        R"("videoCount":109}}})";
    client.answer(route);

    for (std::uint64_t now = 0;
         now < stipple::net::ScriptFetcher::kFailureBackoffMillis + 2000; now += 100) {
        fetcher.tick(now);
    }

    Framebuffer drawn;
    Canvas canvas(drawn);
    STIPPLE_REQUIRE(store.draw("shop", canvas, 33));
    STIPPLE_CHECK(store.problem("shop").empty());
    STIPPLE_CHECK(!(drawn == waiting));

    // 424 subscribers, drawn as "424" at x=14. Pixel-exact, because
    // "it drew something" would pass on the word "fetching".
    Framebuffer expected;
    Canvas expectedCanvas(expected);
    stipple::text::drawLine(expectedCanvas, "424", 14, 0,
                            stipple::text::font5x7(), stipple::colors::kWhite);

    int overlap = 0;
    int wanted = 0;
    for (int y = 0; y < Framebuffer::kHeight; ++y) {
        for (int x = 0; x < Framebuffer::kWidth; ++x) {
            if (expected.at(x, y) != colors::kBlack) {
                ++wanted;
                if (drawn.at(x, y) != colors::kBlack) { ++overlap; }
            }
        }
    }
    STIPPLE_REQUIRE(wanted > 0);
    if (overlap != wanted) {
        std::printf("    [shop] youtube.be drew %d of %d pixels of \"424\"\n",
                    overlap, wanted);
    }
    STIPPLE_CHECK(overlap == wanted);
}

STIPPLE_TEST(ShopScripts, TheDaylightScriptReadsRealSunriseTimes) {
    // The shop gate runs it with no network, where it draws "fetching" and
    // returns before touching the JSON - so nothing else here would notice
    // if Open-Meteo renamed a field or moved the hour within the timestamp.
    //
    // The timestamp parsing is the fragile part: the script reads the hour
    // and minute at fixed offsets in "2026-09-27T07:23", which is correct
    // right up until the API starts returning seconds.
    const std::string source =
        readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/daylight.be");
    STIPPLE_REQUIRE(!source.empty());

    stipple::platform::simulator::SimulatorHttpClient client;
    stipple::net::ScriptFetcher fetcher;
    fetcher.setClient(&client);
    fetcher.setNetworkUp(true);

    // Midday, so the sun is up and the arc has a dot on it.
    stipple::script::ScriptEnvironment environment;
    environment.timeKnown = true;
    environment.hour = 12;
    environment.minute = 30;

    ScriptStore store;
    store.setHttp(&fetcher);
    store.setEnvironment(environment);
    STIPPLE_REQUIRE(store.put("shop", "daylight.be", source) ==
                    stipple::script::ScriptPutResult::Added);

    Framebuffer waiting;
    Canvas waitingCanvas(waiting);
    STIPPLE_REQUIRE(store.draw("shop", waitingCanvas, 0));
    STIPPLE_REQUIRE(fetcher.feedCount() == 1);

    fetcher.tick(0);
    STIPPLE_REQUIRE(!client.asked().empty());

    stipple::platform::simulator::SimulatorHttpClient::Route route;
    route.url = client.asked().front();
    route.latencyMillis = 0;
    route.body =
        R"({"latitude":52.37,"longitude":4.89,"timezone":"Europe/Amsterdam",)"
        R"("daily":{"time":["2026-09-27"],)"
        R"("sunrise":["2026-09-27T07:23"],"sunset":["2026-09-27T19:34"]}})";
    client.answer(route);

    for (std::uint64_t now = 0;
         now < stipple::net::ScriptFetcher::kFailureBackoffMillis + 2000; now += 100) {
        fetcher.tick(now);
    }

    Framebuffer drawn;
    Canvas canvas(drawn);
    STIPPLE_REQUIRE(store.draw("shop", canvas, 33));

    STIPPLE_CHECK(countLit(drawn) > countLit(waiting));
    STIPPLE_CHECK(!(drawn == waiting));
    STIPPLE_CHECK(store.problem("shop").empty());

    // Sunset is 19:34 and the script draws the *next* event, so those digits
    // have to be on the panel. Rendering them separately and comparing beats
    // asserting a pixel count, which would pass on any five characters.
    Framebuffer expected;
    Canvas expectedCanvas(expected);
    // x=8, matching the script: the triangle before it ends at pixel 6.
    // This is pixel-exact on purpose - it caught the time moving by one
    // column when the day-length label was removed, which no "did it draw
    // something" check would have noticed.
    stipple::text::drawLine(expectedCanvas, "19:34", 8, 9,
                            stipple::text::font5x7(), stipple::colors::kWhite);

    int overlap = 0;
    int wanted = 0;
    for (int y = 0; y < Framebuffer::kHeight; ++y) {
        for (int x = 0; x < Framebuffer::kWidth; ++x) {
            if (expected.at(x, y) != colors::kBlack) {
                ++wanted;
                if (drawn.at(x, y) != colors::kBlack) {
                    ++overlap;
                }
            }
        }
    }
    STIPPLE_REQUIRE(wanted > 0);
    if (overlap != wanted) {
        std::printf("    [shop] daylight.be drew %d of %d pixels of \"19:34\"\n",
                    overlap, wanted);
    }
    STIPPLE_CHECK(overlap == wanted);
}

STIPPLE_TEST(ShopScripts, TheWeatherScriptReadsARealOpenMeteoReply) {
    // The script is only useful if it can parse what the API actually sends,
    // and nothing else here would notice if a field were renamed: the shop
    // gate runs it with no network, where it draws "fetching" and returns
    // before touching the JSON.
    //
    // This body is Open-Meteo's real shape, trimmed to the four fields the
    // script asks for.
    const std::string source =
        readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/weather.be");
    STIPPLE_REQUIRE(!source.empty());

    // The URL the script builds. Taken from the script rather than retyped,
    // so a change to the query string cannot leave this testing a URL nobody
    // fetches.
    const std::size_t start = source.find("https://api.open-meteo.com");
    STIPPLE_REQUIRE(start != std::string::npos);

    stipple::platform::simulator::SimulatorHttpClient client;
    stipple::net::ScriptFetcher fetcher;
    fetcher.setClient(&client);
    fetcher.setNetworkUp(true);

    ScriptStore store;
    store.setHttp(&fetcher);
    STIPPLE_REQUIRE(store.put("shop", "weather.be", source) ==
                    stipple::script::ScriptPutResult::Added);

    // One frame to register the follow, so the URL it actually wants can be
    // read back off the fetcher rather than reconstructed here.
    Framebuffer waiting;
    Canvas waitingCanvas(waiting);
    STIPPLE_REQUIRE(store.draw("shop", waitingCanvas, 0));
    // If this fails the script stopped calling http_follow, and everything
    // below would pass trivially on a script that fetches nothing.
    STIPPLE_REQUIRE(fetcher.feedCount() == 1);

    // Whatever URL it asked for, answer that one.
    fetcher.tick(0);
    STIPPLE_REQUIRE(!client.asked().empty());

    stipple::platform::simulator::SimulatorHttpClient::Route route;
    route.url = client.asked().front();
    route.latencyMillis = 0;
    route.body =
        R"({"latitude":52.37,"longitude":4.89,"timezone":"Europe/Amsterdam",)"
        R"("current":{"time":"2026-09-27T14:30","temperature_2m":21.4,"weather_code":61},)"
        R"("daily":{"time":["2026-09-27"],"temperature_2m_max":[23.1],)"
        R"("temperature_2m_min":[12.8]}})";
    client.answer(route);

    // The first request went out before the route existed and failed, so run
    // past the failure backoff to get a second one.
    for (std::uint64_t now = 0;
         now < stipple::net::ScriptFetcher::kFailureBackoffMillis + 2000; now += 100) {
        fetcher.tick(now);
    }

    Framebuffer drawn;
    Canvas canvas(drawn);
    STIPPLE_REQUIRE(store.draw("shop", canvas, 33));

    // It parsed, so it drew a sky and numbers rather than the word "fetching".
    STIPPLE_CHECK(countLit(drawn) > countLit(waiting));
    STIPPLE_CHECK(!(drawn == waiting));

    // And nothing threw on the way. A Berry error here would have disabled
    // the script, and every check above would still have passed on the frame
    // it managed before dying.
    STIPPLE_CHECK(store.problem("shop").empty());
}

// Not a test so much as a way to look at them.
//
// "Does this look right on a 52x16 panel" cannot be asserted, only seen. Set
// STIPPLE_SHOP_FRAMES=<directory> and this writes one raw RGB stream per
// script - every frame, back to back, 52*16*3 bytes each - which
// tooling/site/build-previews.py turns into the animations on the shop page.
//
// Raw rather than PNG, because the consumer is a script that wants pixels and
// putting them through an image format only to take them out again would be
// two conversions to get back where it started.
//
// The frames come from the real engine at the real size. A preview drawn any
// other way would be a picture of something that does not exist.
STIPPLE_TEST(ShopScripts, WriteFramesOnRequest) {
    const char* directory = std::getenv("STIPPLE_SHOP_FRAMES");
    if (directory == nullptr) {
        return;
    }

    // Three seconds at thirty frames. Long enough for the animations here to
    // show what they do and short enough that the page is not carrying
    // megabytes of them.
    constexpr int kFrames = 90;
    constexpr std::uint64_t kFrameMillis = 33;

    stipple::script::ScriptEnvironment environment;
    environment.timeKnown = true;
    environment.hour = 14;
    environment.minute = 37;
    environment.second = 22;
    environment.day = 9;
    environment.month = 11;
    environment.year = 2025;
    environment.weekday = 0;
    environment.batteryKnown = true;
    environment.batteryPercent = 64;
    environment.charging = true;

    // A speaker is present, because a TC002 has one.
    //
    // Without this the audio scripts would each draw their "no speaker"
    // marker into the shop page - a preview advertising a limitation of the
    // machine that rendered it rather than of the device somebody would run
    // it on, which is a worse lie than the one the marker exists to prevent.
    SilentSpeaker speaker;

    // And a broker, for the same reason. A card reading "no broker" would be
    // advertising a limitation of the machine that rendered the GIF.
    //
    // It answers every watch with a plausible reading, which is a stand-in
    // and is labelled as one: the shop cannot know what is on anybody's
    // broker, and the alternative is a card showing the word "waiting" for
    // three seconds.
    NowhereBroker broker;

    // A microphone, hearing something. A visualiser card that read "no mic"
    // would be describing the test runner, not the device.
    stipple::platform::simulator::SimulatorMicrophone microphone;

    // And a network that answers. Same stand-in, same reason: a card showing
    // three seconds of the word "fetching" is a picture of this test runner
    // rather than of a device on somebody's shelf.
    stipple::platform::simulator::SimulatorHttpClient http;
    // Plausible data per API, matched on the host in the URL.
    //
    // One canned body for everything was the first version and stopped
    // working the moment a second API was involved: a weather reply has no
    // subscriber count in it, so the YouTube card showed "fetching" for
    // three seconds. The harness cannot know which URL a card will ask for
    // until it has drawn once, so the routes are registered as the requests
    // appear.
    //
    // Stand-ins, and labelled as such: the shop cannot know what is on
    // anybody's channel.
    const auto answerFor = [](const std::string& url) -> std::string {
        if (url.find("socialcounts") != std::string::npos) {
            return R"({"counters":{"estimation":{"subscriberCount":12400,)"
                   R"("viewCount":982143,"videoCount":109},)"
                   R"("api":{"subscriberCount":12400,"viewCount":982143,)"
                   R"("videoCount":109}}})";
        }
        if (url.find("air-quality") != std::string::npos) {
            return R"({"current":{"time":"2026-09-29T08:00","pm2_5":20.7,)"
                   R"("pm10":24.5,"european_aqi":43}})";
        }
        if (url.find("ipify") != std::string::npos ||
            url.find("checkip") != std::string::npos) {
            // What these services actually return: the address and nothing
            // else. No JSON, no trailing newline worth relying on.
            return "203.0.113.42";
        }
        if (url.find("contributions") != std::string::npos) {
            std::string body = R"({"total":{"lastYear":928},"contributions":[)";
            for (int i = 0; i < 365; ++i) {
                if (i > 0) { body += ','; }
                // A year that looks like somebody's: busier midweek, quiet
                // at the edges, with a couple of dead fortnights.
                int level = (i % 7 == 0 || i % 7 == 6) ? (i % 3 == 0 ? 1 : 0)
                                                       : (1 + (i * 7) % 4);
                if ((i / 14) % 9 == 3) { level = 0; }
                body += R"({"date":"2026-01-01","count":)" + std::to_string(level * 3) +
                        R"(,"level":)" + std::to_string(level) + "}";
            }
            return body + "]}";
        }
        return R"({"current":{"temperature_2m":21.4,"weather_code":61},)"
               R"("daily":{"time":["2026-09-27"],)"
               R"("temperature_2m_max":[23.1],"temperature_2m_min":[12.8],)"
               R"("sunrise":["2026-09-27T07:23"],"sunset":["2026-09-27T19:34"]}})";
    };

    // Registered up front and matched on a fragment of the URL, because the
    // first fetch has to get the right body. Answering it with the wrong one
    // still counts as a success, and the feed would then not ask again for
    // the length of its interval - half an hour, against a three-second
    // card.
    http.answerMatching("socialcounts", 200, answerFor("socialcounts"));
    http.answerMatching("contributions", 200, answerFor("contributions"));
    http.answerMatching("air-quality", 200, answerFor("air-quality"));
    http.answerMatching("ipify", 200, answerFor("ipify"));
    http.answerMatching("checkip", 200, answerFor("checkip"));

    // Anything unrecognised still answers, so a new script that fetches gets
    // a card rather than three seconds of the word "fetching".
    http.setDefaultAnswer(200, answerFor(""));

    for (const Example& example : loadExamples()) {
        if (example.source.empty()) { continue; }

        stipple::mqtt::ScriptGateway gateway;
        gateway.setClient(&broker);
        gateway.setBase("stipple/demo");
        gateway.setConnected(true);

        ScriptStore store;
        store.setEnvironment(environment);
        store.setAudio(&speaker);
        store.setMqtt(&gateway);
        store.setMicrophone(&microphone);

        stipple::net::ScriptFetcher fetcher;
        fetcher.setClient(&http);
        fetcher.setNetworkUp(true);
        store.setHttp(&fetcher);
        if (store.put("shop", example.name, example.source) !=
            stipple::script::ScriptPutResult::Added) {
            continue;
        }

        const std::string stem = example.name.substr(0, example.name.find('.'));
        const std::string path = std::string(directory) + "/" + stem + ".rgb";
        std::FILE* out = std::fopen(path.c_str(), "wb");
        if (out == nullptr) { continue; }

        Framebuffer framebuffer;
        Canvas canvas(framebuffer);

        // Two seconds drawn and thrown away before recording starts.
        //
        // The preview should show the app as you meet it in the carousel,
        // which is never in its first millisecond. Every script that
        // accumulates anything opens on an empty version of itself: a feed
        // has not answered, a scrolling history has not scrolled, a
        // simulation has not settled. A card is three seconds long and
        // spending the first of them on a blank panel wastes a third of it.
        //
        // The clock runs continuously through the warm-up, so nothing sees
        // time jump - which matters, because most of these throttle on
        // now_ms() and a jump would make them skip.
        constexpr int kWarmUp = 64;

        for (int frame = 0; frame < kWarmUp + kFrames; ++frame) {
            // Nothing is pressed here, deliberately.
            //
            // The preview shows what the panel does when nobody is touching
            // it, which is what a visitor's device would be doing. Pressing
            // seemed obviously right - a game previewing its idle screen
            // looked like a waste - and it was wrong twice over: Flappy
            // opened on its game-over screen, and one press put Selenograph
            // into a caption that scrolls for eighteen seconds, so a preview
            // three seconds long never drew the moon the script is for.
            //
            // The compile test above still presses every eleventh frame. That
            // is where on_button needs exercising; this is a photograph.
            environment.monotonicMillis = static_cast<std::uint64_t>(frame) * kFrameMillis;
            store.setEnvironment(environment);
            gateway.setNowMillis(environment.monotonicMillis);

            // A plausible room: a slow swell with a beat on it, so a
            // visualiser has a shape to draw rather than a flat line.
            const int swell = 3000 + (frame * 211) % 9000;
            const int beat = (frame % 15) < 3 ? 12000 : 0;
            microphone.hear(swell + beat);
            fetcher.tick(environment.monotonicMillis);

            // Answer whatever the script asked for on its last frame. A slow
            // walk rather than a constant, so a graph has something to draw
            // and a threshold has something to cross.
            //
            // Plausible per topic where the topic says what it means. One
            // number for everything was the first version, and it made the
            // energy balance meaningless: solar, house load and battery
            // charge were all the same value, so every segment of the bar
            // came out the same width and the picture said nothing. A
            // preview that cannot be wrong is also one that cannot be right.
            for (const std::string& filter : broker.watched) {
                if (filter.find('+') != std::string::npos ||
                    filter.find('#') != std::string::npos) {
                    continue;  // no single topic to invent
                }
                stipple::platform::MqttMessage reading;
                reading.topic = filter;

                // A sunny afternoon with the car plugged in: solar covers the
                // house and most of the car, the battery tops it up, and a
                // little goes back to the grid.
                const int walk = static_cast<int>((frame * 47) % 900);
                if (filter.find("pvPower") != std::string::npos) {
                    reading.payload = std::to_string(4200 + walk);
                } else if (filter.find("homePower") != std::string::npos) {
                    reading.payload = std::to_string(600 + walk / 3);
                } else if (filter.find("gridPower") != std::string::npos) {
                    reading.payload = std::to_string(-400 + walk / 2);
                } else if (filter.find("batterySoc") != std::string::npos) {
                    reading.payload = std::to_string(48 + (frame / 12) % 40);
                } else if (filter.find("batteryPower") != std::string::npos) {
                    reading.payload = std::to_string(-900 + walk / 2);
                } else if (filter.find("chargePower") != std::string::npos) {
                    reading.payload = std::to_string(3300 + walk / 4);
                } else {
                    reading.payload = std::to_string(300 + (frame * 47) % 3400);
                }
                gateway.deliver(reading);
            }

            store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * kFrameMillis);

            if (frame < kWarmUp) {
                continue;
            }

            for (int y = 0; y < Framebuffer::kHeight; ++y) {
                for (int x = 0; x < Framebuffer::kWidth; ++x) {
                    const stipple::Rgb pixel = framebuffer.at(x, y);
                    const unsigned char triple[3] = {pixel.r, pixel.g, pixel.b};
                    std::fwrite(triple, 1, 3, out);
                }
            }
        }
        std::fclose(out);
        std::printf("    [frames] %s: %d frames\n", example.name.c_str(), kFrames);
    }
}

// The built-in apps, for the landing page.
//
// Same format and same reason as WriteFramesOnRequest, but for the apps that
// ship in the firmware rather than the scripts in the library. Set
// STIPPLE_DEFAULT_FRAMES=<directory>.
STIPPLE_TEST(ShopScripts, WriteDefaultAppFramesOnRequest) {
    const char* directory = std::getenv("STIPPLE_DEFAULT_FRAMES");
    if (directory == nullptr) {
        return;
    }

    constexpr int kFrames = 90;
    constexpr std::uint64_t kFrameMillis = 33;

    const auto dump = [&](const char* name, int frames, auto&& draw) {
        const std::string path = std::string(directory) + "/" + name + ".rgb";
        std::FILE* out = std::fopen(path.c_str(), "wb");
        if (out == nullptr) {
            return;
        }
        Framebuffer framebuffer;
        Canvas canvas(framebuffer);
        for (int frame = 0; frame < frames; ++frame) {
            draw(canvas, static_cast<std::uint64_t>(frame) * kFrameMillis);
            for (int y = 0; y < Framebuffer::kHeight; ++y) {
                for (int x = 0; x < Framebuffer::kWidth; ++x) {
                    const stipple::Rgb pixel = framebuffer.at(x, y);
                    const unsigned char triple[3] = {pixel.r, pixel.g, pixel.b};
                    std::fwrite(triple, 1, 3, out);
                }
            }
        }
        std::fclose(out);
        std::printf("    [frames] %s: %d frames\n", name, frames);
    };

    // 14:37:22 UTC, the same moment the library previews use. Two seconds so
    // the colon is seen to blink.
    dump("clock", kFrames, [](Canvas& canvas, std::uint64_t millis) {
        stipple::platform::simulator::SimulatorClock clock;
        clock.setWallClock(1762699042);
        clock.advance(millis);
        stipple::apps::renderClock(canvas, clock, stipple::apps::ClockStyle{});
    });

    stipple::apps::Stopwatch watch;
    watch.press(0);
    dump("stopwatch", kFrames, [&](Canvas& canvas, std::uint64_t millis) {
        stipple::apps::renderStopwatch(canvas, watch, millis,
                                       stipple::apps::StopwatchStyle{});
    });

    stipple::platform::BatteryStatus status;
    status.known = true;
    status.percent = 64;
    status.chargingKnown = true;
    status.charging = true;
    dump("battery", 1, [&](Canvas& canvas, std::uint64_t) {
        stipple::apps::renderBattery(canvas, status, stipple::apps::BatteryStyle{});
    });
}

// Not a test so much as a way to look at them.
//
// "Does this look right on a 52x16 panel" cannot be asserted, only seen. Set
// STIPPLE_SHOP_PREVIEW=<directory>
// sampled frame; without it, it does nothing and costs nothing.
STIPPLE_TEST(ShopScripts, PreviewsOnRequest) {
    const char* directory = std::getenv("STIPPLE_SHOP_PREVIEW");
    if (directory == nullptr) {
        return;
    }

    stipple::script::ScriptEnvironment environment;
    environment.timeKnown = true;
    environment.hour = 14;
    environment.minute = 37;
    environment.second = 22;
    environment.day = 9;
    environment.month = 11;
    environment.year = 2025;
    environment.batteryKnown = true;
    environment.batteryPercent = 64;
    environment.charging = true;

    for (const Example& example : loadExamples()) {
        if (example.source.empty()) { continue; }

        ScriptStore store;
        store.setEnvironment(environment);
        if (store.put("shop", example.name, example.source) !=
            stipple::script::ScriptPutResult::Added) {
            continue;
        }

        Framebuffer framebuffer;
        Canvas canvas(framebuffer);
        const int kFrames[] = {0, 30, 90, 200};
        int previous = 0;
        for (const int target : kFrames) {
            for (int frame = previous; frame < target; ++frame) {
                environment.monotonicMillis = static_cast<std::uint64_t>(frame) * 33u;
                store.setEnvironment(environment);
                store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);
                // Play it, rather than watch it fall. A preview of a game
                // showing its game-over screen is a preview of nothing.
                if (frame % 12 == 0) {
                    store.button("shop", "select");
                }
            }
            previous = target;
            environment.monotonicMillis = static_cast<std::uint64_t>(target) * 33u;
            store.setEnvironment(environment);
            store.draw("shop", canvas, static_cast<std::uint64_t>(target) * 33u);

            std::string stem = example.name.substr(0, example.name.find('.'));
            const std::string path = std::string(directory) + "/" + stem + "-" +
                                     std::to_string(target) + ".png";
            stipple::imageio::writePng(path, framebuffer, 8);
        }
    }
}

// What each script actually costs per frame, against the 200,000 budget.
//
// Set STIPPLE_SCRIPT_COST=1. A number, rather than "it fits" or "it does not":
// a script at 180,000 passes today and fails the first time somebody adds a
// line to it, and the author should be able to see that coming.
STIPPLE_TEST(ShopScripts, InstructionCostProbe) {
    if (std::getenv("STIPPLE_SCRIPT_COST") == nullptr) {
        return;
    }
    for (const Example& example : loadExamples()) {
        if (example.source.empty()) { continue; }

        ScriptStore store;
        stipple::script::ScriptEnvironment environment;
        environment.timeKnown = true;
        environment.hour = 14;
        store.setEnvironment(environment);
        if (store.put("shop", example.name, example.source) !=
            stipple::script::ScriptPutResult::Added) {
            continue;
        }

        Framebuffer framebuffer;
        Canvas canvas(framebuffer);
        // Averaged over many frames, not taken from one.
        //
        // lastInstructions only moves in steps of 65,536 - that is the
        // heartbeat the budget is enforced on - so any single frame can only
        // say "somewhere in this 64K band". Summing over 300 frames and
        // dividing gives about 200 instructions of resolution, which is the
        // difference between optimising and guessing at it.
        constexpr int kFrames = 300;
        std::uint64_t total = 0;
        std::uint32_t worst = 0;
        for (int frame = 0; frame < kFrames; ++frame) {
            environment.monotonicMillis = static_cast<std::uint64_t>(frame) * 33u;
            store.setEnvironment(environment);
            store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);
            const stipple::script::Script* entry = store.find("shop");
            if (entry != nullptr) {
                total += entry->lastInstructions;
                if (entry->lastInstructions > worst) { worst = entry->lastInstructions; }
            }
        }
        std::printf("    [cost] %-18s mean %8llu  worst band %7u  budget %u\n",
                    example.name.c_str(),
                    static_cast<unsigned long long>(total / kFrames), worst,
                    stipple::script::ScriptHost::kInstructionBudget);
    }
}

// Coming back after a long time off the carousel.
//
// now_ms() is the device clock, so a script off screen for hours sees that
// whole gap as one delta the moment it is shown again. One that catches up in
// a loop - an iteration per elapsed second - does tens of thousands of them in
// a single frame and loses it.
//
// That is what happened to Hootie on a real device while every test here
// passed, because nothing here ever left a script off screen: the probes draw
// every frame.
STIPPLE_TEST(ShopScripts, SurvivesComingBackAfterHoursAway) {
    for (const Example& example : loadExamples()) {
        if (example.source.empty()) { continue; }

        ScriptStore store;
        stipple::script::ScriptEnvironment environment;
        environment.timeKnown = true;
        environment.hour = 14;
        environment.batteryKnown = true;
        environment.batteryPercent = 64;
        store.setEnvironment(environment);

        STIPPLE_REQUIRE(store.put("shop", example.name, example.source) ==
                        stipple::script::ScriptPutResult::Added);

        Framebuffer framebuffer;
        Canvas canvas(framebuffer);

        std::uint64_t clock = 0;
        for (int frame = 0; frame < 30; ++frame) {
            clock += 33;
            environment.monotonicMillis = clock;
            store.setEnvironment(environment);
            store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);
        }

        // Eight hours off the carousel, then back. The dwell restarts at zero,
        // which is the part a script cannot use to measure its own absence.
        clock += 8ull * 60ull * 60ull * 1000ull;
        for (int frame = 0; frame < 30; ++frame) {
            environment.monotonicMillis = clock + static_cast<std::uint64_t>(frame) * 33u;
            store.setEnvironment(environment);
            store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);
        }

        const stipple::script::Script* entry = store.find("shop");
        STIPPLE_REQUIRE(entry != nullptr);
        if (!entry->ok) {
            std::printf("    [away] %s stopped: %s\n", example.name.c_str(),
                        entry->problem.c_str());
        }
        STIPPLE_CHECK(entry->ok);
    }
}

// How Hootie actually ages on a carousel.
//
// Set STIPPLE_HOOTIE=1. Ten seconds on screen, two minutes off, repeated -
// which is what a panel with a dozen apps does to it. Prints what is on the
// panel each time it comes round, so the life stages can be watched going
// past at the speed they really go past.
STIPPLE_TEST(ShopScripts, HootieLifecycleTrace) {
    if (std::getenv("STIPPLE_HOOTIE") == nullptr) {
        return;
    }

    const std::string source = readFile(std::string(STIPPLE_SCRIPTS_DIR) + "/hootie.be");
    STIPPLE_REQUIRE(!source.empty());

    ScriptStore store;
    stipple::script::ScriptEnvironment environment;
    environment.timeKnown = true;
    environment.hour = 14;
    store.setEnvironment(environment);
    STIPPLE_REQUIRE(store.put("shop", "hootie", source) ==
                    stipple::script::ScriptPutResult::Added);

    Framebuffer framebuffer;
    Canvas canvas(framebuffer);

    std::uint64_t clock = 500000;  // the device has been up a while
    const std::uint64_t started = clock;

    for (int showing = 0; showing < 14; ++showing) {
        for (int frame = 0; frame < 300; ++frame) {
            environment.monotonicMillis = clock;
            store.setEnvironment(environment);
            store.draw("shop", canvas, static_cast<std::uint64_t>(frame) * 33u);
            clock += 33;
        }

        int lit = 0;
        for (int y = 0; y < Framebuffer::kHeight; ++y) {
            for (int x = 0; x < Framebuffer::kWidth; ++x) {
                if (framebuffer.at(x, y) != colors::kBlack) { ++lit; }
            }
        }
        std::printf("    [life] showing %2d  wall %4llus  lit %3d\n", showing,
                    static_cast<unsigned long long>((clock - started) / 1000), lit);

        clock += 120000;  // off the carousel
    }
}
