// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by nightscout-pixbar/export_stipple.py from golden/manifest.json - do not edit.
//
// The inputs behind every golden frame, so the firmware renderer is tested against
// exactly what the reference renderer drew. Histories are copied verbatim rather
// than regenerated: the reference builds them with float arithmetic, and a second
// implementation of that would be a second thing to get wrong.
#pragma once

#include <cstdint>

namespace stipple {
namespace apps {
namespace glucose {
namespace golden {

struct Point {
    std::int64_t epoch;
    int sgv;
};

struct State {
    const char* name;
    int sgv;
    const char* trend;
    bool hasDelta;
    int delta;
    int minutesAgo;
    int hour;
    int minute;
    bool stale;
    const Point* history;
    int historyCount;
};

struct Frame {
    const char* face;
    const char* state;
    const char* fixture;
    int litPixels;
};

inline constexpr std::int64_t kFixedNow = 1790510400;
inline constexpr int kStaleMinutes = 20;

inline constexpr Point kHistory_in_range[] = {{1790499720, 113}, {1790500020, 115}, {1790500320, 114}, {1790500620, 117}, {1790500920, 115}, {1790501220, 116}, {1790501520, 116}, {1790501820, 118}, {1790502120, 118}, {1790502420, 120}, {1790502720, 119}, {1790503020, 122}, {1790503320, 120}, {1790503620, 121}, {1790503920, 121}, {1790504220, 123}, {1790504520, 124}, {1790504820, 125}, {1790505120, 124}, {1790505420, 127}, {1790505720, 125}, {1790506020, 127}, {1790506320, 126}, {1790506620, 128}, {1790506920, 129}, {1790507220, 130}, {1790507520, 130}, {1790507820, 132}, {1790508120, 130}, {1790508420, 132}, {1790508720, 131}, {1790509020, 134}, {1790509320, 134}, {1790509620, 135}, {1790509920, 135}, {1790510220, 118}};
inline constexpr Point kHistory_warn_high[] = {{1790499720, 191}, {1790500020, 193}, {1790500320, 193}, {1790500620, 197}, {1790500920, 196}, {1790501220, 197}, {1790501520, 198}, {1790501820, 201}, {1790502120, 202}, {1790502420, 204}, {1790502720, 204}, {1790503020, 207}, {1790503320, 206}, {1790503620, 208}, {1790503920, 209}, {1790504220, 211}, {1790504520, 212}, {1790504820, 215}, {1790505120, 215}, {1790505420, 218}, {1790505720, 217}, {1790506020, 219}, {1790506320, 219}, {1790506620, 222}, {1790506920, 223}, {1790507220, 225}, {1790507520, 225}, {1790507820, 229}, {1790508120, 228}, {1790508420, 230}, {1790508720, 230}, {1790509020, 233}, {1790509320, 234}, {1790509620, 236}, {1790509920, 236}, {1790510220, 210}};
inline constexpr Point kHistory_urgent_high[] = {{1790499720, 254}, {1790500020, 257}, {1790500320, 257}, {1790500620, 261}, {1790500920, 261}, {1790501220, 264}, {1790501520, 265}, {1790501820, 268}, {1790502120, 270}, {1790502420, 273}, {1790502720, 274}, {1790503020, 278}, {1790503320, 277}, {1790503620, 280}, {1790503920, 281}, {1790504220, 285}, {1790504520, 286}, {1790504820, 289}, {1790505120, 290}, {1790505420, 294}, {1790505720, 294}, {1790506020, 296}, {1790506320, 297}, {1790506620, 301}, {1790506920, 302}, {1790507220, 306}, {1790507520, 306}, {1790507820, 310}, {1790508120, 310}, {1790508420, 312}, {1790508720, 314}, {1790509020, 317}, {1790509320, 319}, {1790509620, 320}, {1790509920, 320}, {1790510220, 287}};
inline constexpr Point kHistory_warn_low[] = {{1790499720, 82}, {1790500020, 83}, {1790500320, 81}, {1790500620, 83}, {1790500920, 80}, {1790501220, 80}, {1790501520, 79}, {1790501820, 80}, {1790502120, 79}, {1790502420, 80}, {1790502720, 78}, {1790503020, 80}, {1790503320, 77}, {1790503620, 77}, {1790503920, 76}, {1790504220, 77}, {1790504520, 76}, {1790504820, 77}, {1790505120, 75}, {1790505420, 77}, {1790505720, 74}, {1790506020, 74}, {1790506320, 73}, {1790506620, 74}, {1790506920, 73}, {1790507220, 74}, {1790507520, 72}, {1790507820, 74}, {1790508120, 71}, {1790508420, 71}, {1790508720, 70}, {1790509020, 71}, {1790509320, 70}, {1790509620, 71}, {1790509920, 69}, {1790510220, 66}};
inline constexpr Point kHistory_urgent_low[] = {{1790499720, 76}, {1790500020, 76}, {1790500320, 74}, {1790500620, 75}, {1790500920, 72}, {1790501220, 71}, {1790501520, 69}, {1790501820, 70}, {1790502120, 69}, {1790502420, 69}, {1790502720, 66}, {1790503020, 67}, {1790503320, 64}, {1790503620, 64}, {1790503920, 62}, {1790504220, 62}, {1790504520, 61}, {1790504820, 61}, {1790505120, 59}, {1790505420, 60}, {1790505720, 56}, {1790506020, 56}, {1790506320, 54}, {1790506620, 55}, {1790506920, 53}, {1790507220, 53}, {1790507520, 51}, {1790507820, 52}, {1790508120, 49}, {1790508420, 48}, {1790508720, 46}, {1790509020, 47}, {1790509320, 46}, {1790509620, 46}, {1790509920, 43}, {1790510220, 48}};
inline constexpr Point kHistory_stale[] = {{1790499720, 101}, {1790500020, 103}, {1790500320, 102}, {1790500620, 105}, {1790500920, 103}, {1790501220, 104}, {1790501520, 104}, {1790501820, 106}, {1790502120, 106}, {1790502420, 107}, {1790502720, 106}, {1790503020, 109}, {1790503320, 107}, {1790503620, 108}, {1790503920, 108}, {1790504220, 110}, {1790504520, 110}, {1790504820, 112}, {1790505120, 111}, {1790505420, 113}, {1790505720, 111}, {1790506020, 113}, {1790506320, 112}, {1790506620, 114}, {1790506920, 114}, {1790507220, 116}, {1790507520, 115}, {1790507820, 118}, {1790508120, 116}, {1790508420, 117}, {1790508720, 116}};
inline constexpr Point kHistory_rising_45[] = {{1790499720, 141}, {1790500020, 143}, {1790500320, 143}, {1790500620, 146}, {1790500920, 144}, {1790501220, 146}, {1790501520, 146}, {1790501820, 148}, {1790502120, 149}, {1790502420, 151}, {1790502720, 150}, {1790503020, 153}, {1790503320, 152}, {1790503620, 153}, {1790503920, 153}, {1790504220, 156}, {1790504520, 156}, {1790504820, 158}, {1790505120, 158}, {1790505420, 161}, {1790505720, 159}, {1790506020, 161}, {1790506320, 161}, {1790506620, 163}, {1790506920, 164}, {1790507220, 166}, {1790507520, 165}, {1790507820, 168}, {1790508120, 167}, {1790508420, 168}, {1790508720, 168}, {1790509020, 171}, {1790509320, 171}, {1790509620, 173}, {1790509920, 173}, {1790510220, 152}};
inline constexpr Point kHistory_falling_45[] = {{1790499720, 96}, {1790500020, 97}, {1790500320, 95}, {1790500620, 98}, {1790500920, 95}, {1790501220, 96}, {1790501520, 95}, {1790501820, 96}, {1790502120, 96}, {1790502420, 97}, {1790502720, 96}, {1790503020, 98}, {1790503320, 95}, {1790503620, 96}, {1790503920, 95}, {1790504220, 97}, {1790504520, 96}, {1790504820, 97}, {1790505120, 96}, {1790505420, 98}, {1790505720, 96}, {1790506020, 96}, {1790506320, 95}, {1790506620, 97}, {1790506920, 97}, {1790507220, 98}, {1790507520, 96}, {1790507820, 98}, {1790508120, 96}, {1790508420, 97}, {1790508720, 96}, {1790509020, 97}, {1790509320, 97}, {1790509620, 98}, {1790509920, 97}, {1790510220, 88}};
inline constexpr Point kHistory_no_trend[] = {{1790499720, 131}, {1790500020, 132}, {1790500320, 131}, {1790500620, 134}, {1790500920, 132}, {1790501220, 133}, {1790501520, 132}, {1790501820, 134}, {1790502120, 134}, {1790502420, 136}, {1790502720, 135}, {1790503020, 137}, {1790503320, 135}, {1790503620, 136}, {1790503920, 136}, {1790504220, 138}, {1790504520, 138}, {1790504820, 139}, {1790505120, 138}, {1790505420, 141}, {1790505720, 139}, {1790506020, 140}, {1790506320, 139}, {1790506620, 141}, {1790506920, 141}, {1790507220, 143}, {1790507520, 142}, {1790507820, 144}, {1790508120, 142}, {1790508420, 143}, {1790508720, 143}, {1790509020, 145}, {1790509320, 145}, {1790509620, 146}, {1790509920, 145}, {1790510220, 131}};

inline constexpr int kStateCount = 9;
inline constexpr State kStates[kStateCount] = {
    {"in-range", 118, "FLAT", true, 2, 3, 14, 32, false, kHistory_in_range, 36},
    {"warn-high", 210, "SINGLE_UP", true, 12, 4, 21, 7, false, kHistory_warn_high, 36},
    {"urgent-high", 287, "DOUBLE_UP", true, 21, 2, 22, 15, false, kHistory_urgent_high, 36},
    {"warn-low", 66, "SINGLE_DOWN", true, -9, 3, 3, 41, false, kHistory_warn_low, 36},
    {"urgent-low", 48, "DOUBLE_DOWN", true, -15, 2, 3, 58, false, kHistory_urgent_low, 36},
    {"stale", 104, "FLAT", true, 0, 27, 7, 12, true, kHistory_stale, 31},
    {"rising-45", 152, "FORTY_FIVE_UP", true, 6, 1, 9, 5, false, kHistory_rising_45, 36},
    {"falling-45", 88, "FORTY_FIVE_DOWN", false, 0, 6, 17, 48, false, kHistory_falling_45, 36},
    {"no-trend", 131, "NONE", false, 0, 3, 12, 0, false, kHistory_no_trend, 36},
};

inline constexpr int kFrameCount = 54;
inline constexpr Frame kFrames[kFrameCount] = {
    {"hero", "in-range", "glucose-hero--in-range", 171},
    {"hero", "warn-high", "glucose-hero--warn-high", 206},
    {"hero", "urgent-high", "glucose-hero--urgent-high", 204},
    {"hero", "warn-low", "glucose-hero--warn-low", 162},
    {"hero", "urgent-low", "glucose-hero--urgent-low", 168},
    {"hero", "stale", "glucose-hero--stale", 47},
    {"hero", "rising-45", "glucose-hero--rising-45", 175},
    {"hero", "falling-45", "glucose-hero--falling-45", 163},
    {"hero", "no-trend", "glucose-hero--no-trend", 156},
    {"hero-delta", "in-range", "glucose-hero-delta--in-range", 171},
    {"hero-delta", "warn-high", "glucose-hero-delta--warn-high", 206},
    {"hero-delta", "urgent-high", "glucose-hero-delta--urgent-high", 200},
    {"hero-delta", "warn-low", "glucose-hero-delta--warn-low", 185},
    {"hero-delta", "urgent-low", "glucose-hero-delta--urgent-low", 198},
    {"hero-delta", "stale", "glucose-hero-delta--stale", 51},
    {"hero-delta", "rising-45", "glucose-hero-delta--rising-45", 171},
    {"hero-delta", "falling-45", "glucose-hero-delta--falling-45", 169},
    {"hero-delta", "no-trend", "glucose-hero-delta--no-trend", 170},
    {"hero-graph", "in-range", "glucose-hero-graph--in-range", 186},
    {"hero-graph", "warn-high", "glucose-hero-graph--warn-high", 197},
    {"hero-graph", "urgent-high", "glucose-hero-graph--urgent-high", 182},
    {"hero-graph", "warn-low", "glucose-hero-graph--warn-low", 154},
    {"hero-graph", "urgent-low", "glucose-hero-graph--urgent-low", 153},
    {"hero-graph", "stale", "glucose-hero-graph--stale", 56},
    {"hero-graph", "rising-45", "glucose-hero-graph--rising-45", 175},
    {"hero-graph", "falling-45", "glucose-hero-graph--falling-45", 167},
    {"hero-graph", "no-trend", "glucose-hero-graph--no-trend", 169},
    {"clock", "in-range", "glucose-clock--in-range", 180},
    {"clock", "warn-high", "glucose-clock--warn-high", 194},
    {"clock", "urgent-high", "glucose-clock--urgent-high", 195},
    {"clock", "warn-low", "glucose-clock--warn-low", 166},
    {"clock", "urgent-low", "glucose-clock--urgent-low", 179},
    {"clock", "stale", "glucose-clock--stale", 93},
    {"clock", "rising-45", "glucose-clock--rising-45", 200},
    {"clock", "falling-45", "glucose-clock--falling-45", 170},
    {"clock", "no-trend", "glucose-clock--no-trend", 171},
    {"big-graph", "in-range", "glucose-big-graph--in-range", 139},
    {"big-graph", "warn-high", "glucose-big-graph--warn-high", 145},
    {"big-graph", "urgent-high", "glucose-big-graph--urgent-high", 156},
    {"big-graph", "warn-low", "glucose-big-graph--warn-low", 124},
    {"big-graph", "urgent-low", "glucose-big-graph--urgent-low", 134},
    {"big-graph", "stale", "glucose-big-graph--stale", 58},
    {"big-graph", "rising-45", "glucose-big-graph--rising-45", 133},
    {"big-graph", "falling-45", "glucose-big-graph--falling-45", 134},
    {"big-graph", "no-trend", "glucose-big-graph--no-trend", 128},
    {"no-data", "in-range", "glucose-no-data--in-range", 112},
    {"no-data", "warn-high", "glucose-no-data--warn-high", 113},
    {"no-data", "urgent-high", "glucose-no-data--urgent-high", 112},
    {"no-data", "warn-low", "glucose-no-data--warn-low", 112},
    {"no-data", "urgent-low", "glucose-no-data--urgent-low", 112},
    {"no-data", "stale", "glucose-no-data--stale", 139},
    {"no-data", "rising-45", "glucose-no-data--rising-45", 108},
    {"no-data", "falling-45", "glucose-no-data--falling-45", 120},
    {"no-data", "no-trend", "glucose-no-data--no-trend", 112},
};

}  // namespace golden
}  // namespace glucose
}  // namespace apps
}  // namespace stipple
